---
# tasks file for role_nrpe_check_podman

- name: Ensure check_podman is installed
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/lib64/nagios/plugins/
    mode: '0755'
  loop:
    - check_podman
- name: Show containers that should run on target host
  ansible.builtin.debug:
    msg: host {{ inventory_hostname }} has containers {{ containers }}
  when: containers is defined
- name: Show pods that should run on target host
  ansible.builtin.debug:
    msg: host {{ inventory_hostname }} has pods {{ pods }}
  when: pods is defined
- name: Ensure check_podman.cfg is installed
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/nrpe.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - check_podman.cfg
  notify: nrpe reload
- name: Ensure sudo rules are in place
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/sudoers.d/
    mode: '0400'
    validate: visudo -cf %s
  loop:
    - 10_nrpe
- name: Ensure selinux policy is applied - part 01
  ansible.builtin.seboolean:
    name: nagios_run_sudo
    state: true
    persistent: true

...
